
const animalCrossingDeck = {
  name: "Animal Crossing Deck",
  cards: [
    {
      id: 43,
      name: "Rover",
      cost: 1,
      power: 3,
      img: "/cardImages/animalcrossing/Rover.png",
      ability: ["addEnergy", 2],
      description: "Add one bonus energy on your next turn.",
      cardPosition: "hand",
      deck: "animal-crossing",
      locationBonus: false,
    },
    {
      id: 44,
      name: "Redd",
      cost: 1,
      power: 5,
      img: "/cardImages/animalcrossing/Redd.png",
      ability: ["drawCards", 1],
      description: "Draw an extra card on your next turn.",
      cardPosition: "hand",
      deck: "animal-crossing",
      locationBonus: false,
    },
    {
      id: 45,
      name: "Tom Nook",
      cost: 1,
      power: 5,
      img: "/cardImages/animalcrossing/Tom_Nook.png",
      ability: ["addPower", 1],
      description: "Give all friendly cards in this location +1 power.",
      cardPosition: "hand",
      deck: "animal-crossing",
      locationBonus: false,
    },
    {
      id: 46,
      name: "K.K. Slider",
      cost: 3,
      power: 7,
      img: "/cardImages/animalcrossing/KK_Slider.png",
      ability: ["shuffleHandIntoDeck", 3],
      description:
        "Shuffle your hand back into your deck and draw three new cards.",
      cardPosition: "hand",
      deck: "animal-crossing",
      locationBonus: false,
    },
    {
      id: 47,
      name: "Blathers",
      cost: 2,
      power: 5,
      img: "/cardImages/animalcrossing/Blathers.png",
      ability: ["playCardFromDeck", 1],
      description:
        "On your next turn, place a card from your deck into this location.",
      cardPosition: "hand",
      deck: "animal-crossing",
      locationBonus: false,
    },
    {
      id: 48,
      name: "Resetti",
      cost: 6,
      power: 15,
      img: "/cardImages/animalcrossing/Resetti.png",
      ability: ["addPower", 4],
      description: "Give all friendly cards in this location +4 power.",
      cardPosition: "hand",
      deck: "animal-crossing",
      locationBonus: false,
    },
  ],
};

export default animalCrossingDeck;
