

const fireflyDeck = {
  name: "Firefly Deck",
  cards: [
    {
      id: 31,
      name: "Zoe",
      cost: 1,
      power: 2,
      img: "cardImages/firefly/zoe.webp",
      ability: ["addEnergy", 1],
      description: "Add 1 bonus energy on your next turn.",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 32,
      name: "Inara",
      cost: 2,
      power: 5,
      img: "cardImages/firefly/inara.jpg",
      ability: ["drawCards", 1],
      description: "Draw an extra card on your next turn.",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 33,
      name: "Jayne",
      cost: 3,
      power: 7,
      img: "cardImages/firefly/jayne.jpg",
      ability: ["addPower", 1],
      description: "Give all friendly cards in this location +1 power.",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 34,
      name: "Kaylee",
      cost: 3,
      power: 7,
      img: "cardImages/firefly/kaylee.webp",
      ability: ["shuffleHandIntoDeck", 3],
      description:
        "Shuffle your hand back into your deck and draw three new cards.",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 35,
      name: "Wash",
      cost: 4,
      power: 10,
      img: "cardImages/firefly/wash.webp",
      ability: ["playCardFromDeck", 1],
      description:
        "On your next turn, place a card from your deck into this location.",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 36,
      name: "Mal",
      cost: 6,
      power: 15,
      img: "cardImages/firefly/mal.jpg",
      ability: ["addPower", 4],
      description: "Give all friendly cards in this location +4 power.",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
  ],
};

export default fireflyDeck;
