import abilities from "../abilities.js";

const fireflyDeck = {
  name: "Firefly Deck",
  cards: [
    {
      id: 31,
      name: "Zoe",
      cost: 1,
      power: 2,
      img: "https://static.wikia.nocookie.net/headhuntersholosuite/images/b/be/Zoe_Washburne_001.jpg",
      ability: ["addEnergy", 1],
      description: "Add a bonus energy on your next turn",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 32,
      name: "Inara",
      cost: 2,
      power: 5,
      img: "https://static.tvmaze.com/uploads/images/medium_portrait/1/2603.jpg",
      ability: ["drawCards", 1],
      description: "Draw a card",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 33,
      name: "Jayne",
      cost: 3,
      power: 7,
      img: "https://mindmatters.ai/wp-content/uploads/sites/2/2022/03/Jayne-Cobb-played-by-Adam-Baldwin.jpg",
      ability: ["addPower", 2],
      description: "Give all friendly cards in this location +2 power",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 34,
      name: "Kaylee",
      cost: 3,
      power: 7,
      img: "https://static.wikia.nocookie.net/firefly/images/4/44/Kaylee_closeup.jpg",
      ability: ["shuffleHandIntoDeck", 3],
      description:
        "Shuffle your hand back into your deck and draw three new cards",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 35,
      name: "Wash",
      cost: 4,
      power: 10,
      img: "https://static.wikia.nocookie.net/firefly/images/6/68/Wash03.jpg",
      ability: ["playCardFromDeck", 1],
      description:
        "On your next turn, place a card from your deck into this location",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
    {
      id: 36,
      name: "Mal",
      cost: 6,
      power: 15,
      img: "https://upload.wikimedia.org/wikipedia/en/1/13/MalReynoldsFirefly.JPG",
      ability: ["addPower", 4],
      description: "Give all friendly cards in this location +4 power",
      cardPosition: "hand",
      deck: "firefly",
      locationBonus: false,
    },
  ],
};

export default fireflyDeck;
