import abilities from "../abilities.js";

const friendsDeck = {
  name: "Friends Deck",
  cards: [
    {
      id: 37,
      name: "Joey",
      cost: 1,
      power: 2,
      img: "https://static.wikia.nocookie.net/friends/images/f/f5/JoeyTribbiani.jpg",
      ability: ["addEnergy", 1],
      description: "Add a bonus energy on your next turn",
      cardPosition: "hand",
      deck: "friends",
      locationBonus: false,
    },
    {
      id: 38,
      name: "Ross",
      cost: 2,
      power: 5,
      img: "https://static.wikia.nocookie.net/friends/images/0/0b/RossGeller.jpg",
      ability: ["drawCards", 1],
      description: "Draw a card",
      cardPosition: "hand",
      deck: "friends",
      locationBonus: false,
    },
    {
      id: 39,
      name: "Chandler",
      cost: 3,
      power: 7,
      img: "https://static.wikia.nocookie.net/friends/images/4/48/Chandler_Bing_portrait.jpg",
      ability: ["addPower", 2],
      description: "Give all friendly cards in this location +2 power",
      cardPosition: "hand",
      deck: "friends",
      locationBonus: false,
    },
    {
      id: 40,
      name: "Phoebe",
      cost: 3,
      power: 7,
      img: "https://static.wikia.nocookie.net/friends/images/3/30/PhoebeBuffay.jpg",
      ability: ["shuffleHandIntoDeck", 3],
      description:
        "Shuffle your hand back into your deck and draw three new cards",
      cardPosition: "hand",
      deck: "friends",
      locationBonus: false,
    },
    {
      id: 41,
      name: "Monica",
      cost: 4,
      power: 10,
      img: "https://static.wikia.nocookie.net/friends/images/2/2f/Monica_Geller-Bing_Season_10.png",
      ability: ["playCardFromDeck", 1],
      description:
        "On your next turn, place a card from your deck into this location",
      cardPosition: "hand",
      deck: "friends",
      locationBonus: false,
    },
    {
      id: 42,
      name: "Rachel",
      cost: 6,
      power: 15,
      img: "https://static.wikia.nocookie.net/friends/images/f/f7/Rachel_Greene.jpg",
      ability: ["addPower", 4],
      description: "Give all friendly cards in this location +4 power",
      cardPosition: "hand",
      deck: "friends",
      locationBonus: false,
    },
  ],
};

export default friendsDeck;
