import abilities from "../abilities.js";

const pusheenDeck = {
  name: "Pusheen Deck",
  cards: [
    {
      id: 7,
      name: "Pip",
      cost: 1,
      power: 1,
      img: "/cardImages/pusheen/pip.jpeg",
      ability: ['drawCards', 2],
      description: "Draw two cards",
      cardPosition: "hand",
      deck: "pusheen",
    },
    {
      id: 8,
      name: "Stormy",
      cost: 1,
      power: 3,
      img: "/cardImages/pusheen/stormy.jpeg",
      ability: ['drawCards', 3],
      description: "Draw three cards",
      cardPosition: "hand",
      deck: "pusheen",
    },
    {
      id: 9,
      name: "Pusheen",
      cost: 2,
      power: 5,
      img: "/cardImages/pusheen/pusheen.jpeg",
      ability: ['addPower', 3],
      description: "Give all friendly card in this location +3 power",
      cardPosition: "hand",
      deck: "pusheen",
    },
    {
      id: 10,
      name: "Dragonsheen",
      cost: 3,
      power: 7,
      img: "/cardImages/pusheen/dragonsheen.gif",
      ability: ['addPower', 4],
      description: abilities.addPower.description,
      cardPosition: "hand",
      deck: "pusheen",
    },
    {
      id: 11,
      name: "Sloth",
      cost: 6,
      power: 15,
      img: "/cardImages/pusheen/sloth.jpeg",
      ability: ['addPower', 5],
      description: abilities.addPower.description,
      cardPosition: "hand",
      deck: "pusheen",
    },
    {
      id: 12,
      name: "Pusheenicorn",
      cost: 5,
      power: 12,
      img: "/cardImages/pusheen/super_pusheenicorn.jpeg",
      ability: ['addPower', 6],
      description: abilities.addPower.description,
      cardPosition: "hand",
      deck: "pusheen",
    },
  ],
};

export default pusheenDeck;
