[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['cd snap-up-app && npm install --force && cd .. && cd server && npm install']

[phases.build]
cmds =  ['cd snap-up-app && npm run build']

[start]
cmd = 'cd server && npm run start'