const oppLeftCardZone = [
  {
    id: 1,
    name: "Chucky",
    cost: 1,
    power: 1,
    img: "/cardImages/horror/chucky.png",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "horror",
  },
  {
    id: 2,
    name: "Freddy Krueger",
    cost: 2,
    power: 3,
    img: "/cardImages/horror/freddy.png",
    //ability: abilities[0],
    cardPosition: "hand",
    deck: "horror",
  },
  {
    id: 3,
    name: "Leatherface",
    cost: 3,
    power: 5,
    img: "/cardImages/horror/leatherface.png",
    //ability: abilities[0],
    cardPosition: "hand",
    deck: "horror",
  },
  {
    id: 4,
    name: "Pinhead",
    cost: 4,
    power: 7,
    img: "/cardImages/horror/pinhead.png",
    //ability: abilities[0],
    cardPosition: "hand",
    deck: "horror",
  },
];

const oppMiddleCardZone = [
  {
    id: 13,
    name: "Tuxedo Mask",
    cost: 1,
    power: 0,
    img: "/cardImages/sailor/tuxedo_mask.jpg",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "sailor-moon",
  },
  {
    id: 14,
    name: "Sailor Mercury",
    cost: 1,
    power: 3,
    img: "/cardImages/sailor/sailor_mercury.jpg",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "sailor-moon",
  },
  {
    id: 15,
    name: "Sailor Mars",
    cost: 2,
    power: 5,
    img: "/cardImages/sailor/sailor_mars.jpg",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "sailor-moon",
  },
  {
    id: 16,
    name: "Sailor Jupiter",
    cost: 3,
    power: 7,
    img: "/cardImages/sailor/sailor_jupiter.jpg",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "sailor-moon",
  },
];

const oppRightCardZone = [
  {
    id: 9,
    name: "Pusheen",
    cost: 2,
    power: 5,
    img: "/cardImages/pusheen/pusheen.jpeg",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "pusheen",
  },
  {
    id: 10,
    name: "Dragonsheen",
    cost: 3,
    power: 7,
    img: "/cardImages/pusheen/dragonsheen.jpeg",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "pusheen",
  },
  {
    id: 11,
    name: "Sloth",
    cost: 6,
    power: 15,
    img: "/cardImages/pusheen/sloth.jpeg",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "pusheen",
  },
  {
    id: 12,
    name: "Pusheenicorn",
    cost: 5,
    power: 12,
    img: "/cardImages/pusheen/super_pusheenicorn.jpeg",
    // ability: abilities[0],
    cardPosition: "hand",
    deck: "pusheen",
  },
];

module.exports = { oppLeftCardZone, oppRightCardZone, oppMiddleCardZone };
